// <auto-generated />
using System;
using Aihrly.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Aihrly.Migrations
{
    [DbContext(typeof(AihrlyDbContext))]
    [Migration("20260430003540_FixDuplicateFkColumns")]
    partial class FixDuplicateFkColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Aihrly.Models.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssessmentComment")
                        .HasColumnType("text");

                    b.Property<int?>("AssessmentScore")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("AssessmentUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AssessmentUpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("CandidateEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CandidateName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CoverLetter")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CultureFitComment")
                        .HasColumnType("text");

                    b.Property<int?>("CultureFitScore")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CultureFitUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CultureFitUpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("InterviewComment")
                        .HasColumnType("text");

                    b.Property<int?>("InterviewScore")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("InterviewUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("InterviewUpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentUpdatedBy");

                    b.HasIndex("CultureFitUpdatedBy");

                    b.HasIndex("InterviewUpdatedBy");

                    b.HasIndex("JobId", "CandidateEmail")
                        .IsUnique();

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("Aihrly.Models.ApplicationNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("CreatedBy");

                    b.ToTable("ApplicationNotes");
                });

            modelBuilder.Entity("Aihrly.Models.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("Aihrly.Models.StageHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ChangedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("FromStage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ToStage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("ChangedBy");

                    b.ToTable("StageHistories");
                });

            modelBuilder.Entity("Aihrly.Models.TeamMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("TeamMembers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Email = "sarah@aihrly.com",
                            Name = "Sarah Chen",
                            Role = "recruiter"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Email = "marcus@aihrly.com",
                            Name = "Marcus Johnson",
                            Role = "hiring_manager"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Email = "priya@aihrly.com",
                            Name = "Priya Patel",
                            Role = "recruiter"
                        });
                });

            modelBuilder.Entity("Aihrly.Models.Application", b =>
                {
                    b.HasOne("Aihrly.Models.TeamMember", null)
                        .WithMany()
                        .HasForeignKey("AssessmentUpdatedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Aihrly.Models.TeamMember", null)
                        .WithMany()
                        .HasForeignKey("CultureFitUpdatedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Aihrly.Models.TeamMember", null)
                        .WithMany()
                        .HasForeignKey("InterviewUpdatedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Aihrly.Models.Job", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Aihrly.Models.ApplicationNote", b =>
                {
                    b.HasOne("Aihrly.Models.Application", null)
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aihrly.Models.TeamMember", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("Aihrly.Models.StageHistory", b =>
                {
                    b.HasOne("Aihrly.Models.Application", null)
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aihrly.Models.TeamMember", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChangedByUser");
                });
#pragma warning restore 612, 618
        }
    }
}
